on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Copy files to EC2
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.SSH_KEY }}
        source: "index.php" # Path to your application code
        target: /var/www/html  # Apache web server root directory
    - name: Restart Apache
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
        USERNAME: ${{ secrets.EC2_USER }}
      run: |
        echo "$SSH_PRIVATE_KEY" > key.pem
        chmod 600 key.pem

        # Use SSH to connect to the EC2 instance and restart Apache
        ssh -i key.pem -o StrictHostKeyChecking=no $USERNAME@$EC2_HOST "sudo systemctl restart httpd"
